[build]
base = "."
command = "yarn build"
publish = "./build/"

[build.environment]
REACT_APP_API_URL = "https://buscafe-backend.herokuapp.com/"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
